### ISSUE TITLE
Money Stuck

### ISSUE THREAD

**Issue by DougJudy69** [Manliketjb/market#2]
![Screenshot 2021-11-03 133926](https://user-images.githubusercontent.com/92779892/139970300-17743993-96f2-4f84-94d3-80529436ebf2.png)

money suck top right.

wanna make it go away or just remove completely

**Comment by Manliketjb** [comment]
> ![Screenshot 2021-11-03 133926](https://user-images.githubusercontent.com/92779892/139970300-17743993-96f2-4f84-94d3-80529436ebf2.png)
> 
> money suck top right.
> 
> wanna make it go away or just remove completely

its a qb-hud issue, it doesn't like cryto

**Comment by DougJudy69** [comment]
fast as thanks
